#!/usr/bin/zsh
# This hook is sourced after this virtualenv is activated.
#
PROJECT_PATH=$HOME/projects/CovidGuard-F/ens-server/server
cd $PROJECT_PATH
export PYTHON_PATH=$PYTHONPATH:$PROJECT_PATH
export CLOUDSDK_CORE_PROJECT=ens-server

