#!/usr/bin/zsh
# This hook is sourced after this virtualenv is activated.

cd $HOME/projects/CovidGuard-F/verification-server/server
export PYTHONPATH=$HOME/projects/CovidGuard-F/verification-server/server:$PYTHONPATH

export CLOUDSDK_CORE_PROJECT=covidgaurd-285412
